/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2015-09-21 15:29:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import Modelo.Vendedor;
import Modelo.Regiao;
import Modelo.Venda;

public final class CadastroVendas_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Cadastro de Vendas</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form action=\"CadastroVendas\" method=\"post\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<h1>Cadastro de Vendas</h1>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tVendedor:\r\n");
      out.write("\t\t<select name=\"vendedor\">\r\n");
      out.write("\t\t");

			ArrayList<Vendedor> listaVendedor = (ArrayList<Vendedor>) session.getAttribute("listaVendedor");
			ArrayList<Venda> listaVendas = (ArrayList<Venda>) session.getAttribute("listaVendas");	
		
			if(listaVendedor != null){
				for(int i = 0; i < listaVendedor.size(); i++){
				
      out.write("\r\n");
      out.write("\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(listaVendedor.get(i).getNome());
      out.write("</option>\r\n");
      out.write("\t\t\t\t");
	
				}
			}	
			
      out.write("\t\r\n");
      out.write("\t\t</select><br><br>\r\n");
      out.write("\t\tValor: <input type=\"text\" name=\"valor\"><br><br>\r\n");
      out.write("\t\tRegiao:\r\n");
      out.write("\t\t<select name=\"regiao\">\r\n");
      out.write("\t\t\t");

				for(Regiao regiao: Regiao.values()){
				
      out.write("\t\r\n");
      out.write("\t\t\t\t\t<option value = \"");
      out.print(regiao.name());
      out.write('"');
      out.write('>');
      out.print(regiao.name());
      out.write("</option>\r\n");
      out.write("\t\t\t\t");
	
				}
			
      out.write("\r\n");
      out.write("\t\t</select><br><br>\r\n");
      out.write("\t\t<input type=\"submit\" name=\"btnSubmit\" value=\"salvar\"><br><br>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!--Fim o formulario-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<table border=\"1\" style=\"width:30%\">\r\n");
      out.write("\t\t\t<thead>\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<th>NUMERO</th>\r\n");
      out.write("\t\t\t\t\t<th>VENDEDOR</th>\r\n");
      out.write("\t\t\t\t\t<th>VALOR</th>\r\n");
      out.write("\t\t\t\t\t<th>REGIAO</th>\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t</thead>\r\n");
      out.write("\t\t\t");

				if(listaVendas != null){	
					for(Venda vendas : listaVendas){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t\t\t<td><center>");
      out.print( vendas.getNumeroVenda() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><center>");
      out.print( vendas.getVendedor().getNome() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><center>");
      out.print( vendas.getValorVenda() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t\t\t<td><center>");
      out.print( vendas.getRegiao() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t");
	
					}
				}
			
      out.write("\r\n");
      out.write("\t\t</table>\r\n");
      out.write("\t\t<br><br><a href=\"Menu.jsp\">VOLTAR</a>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
