/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.9
 * Generated at: 2015-09-24 19:41:06 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import Modelo.Vendedor;
import Modelo.Venda;

public final class RelatorioVendasVendedor_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("\t<title>Relatorio por Vendedor</title>\r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body>\r\n");
      out.write("\t\t<form action=\"RelatorioVendasVendedor\" method=\"post\">\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\t<h1>Relatório de Vendas por Vendedor</h1><br>\r\n");
      out.write("\t\t\tVendedor:\r\n");
      out.write("\t\t\t<select name=\"vendedor\">\r\n");
      out.write("\t\t\t");

				ArrayList<Vendedor> listaVendedor = (ArrayList<Vendedor>) session.getAttribute("listaVendedor");	
			
				if(listaVendedor != null){
					for(int i = 0; i < listaVendedor.size(); i++){
					
      out.write("\r\n");
      out.write("\t\t\t\t\t\t<option value=\"");
      out.print(i);
      out.write('"');
      out.write('>');
      out.print(listaVendedor.get(i).getNome());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t");
	
					}
				}	
				
      out.write("\t\r\n");
      out.write("\t\t\t</select><br><br>\r\n");
      out.write("\t\t\t<input type=\"submit\" name=\"btnSubmit\" value=\"Gerar Relatório\"><br><br><br>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t\t<!--Fim o formulario-->\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<!--Inicio da definicao da tabela-->\r\n");
      out.write("\t\t<table border=\"1\" style=\"width:30%\">\r\n");
      out.write("\t\t<thead>\r\n");
      out.write("\t\t\t<tr>\r\n");
      out.write("\t\t\t\t<th>NUMERO</th>\r\n");
      out.write("\t\t\t\t<th>VALOR</th>\r\n");
      out.write("\t\t\t\t<th>REGIAO</th>\r\n");
      out.write("\t\t\t</tr>\r\n");
      out.write("\t\t</thead>\r\n");
      out.write("\t\t");

		Vendedor vendedor = (Vendedor) session.getAttribute("v");
		int qtde = 0;
		double total = 0;
		
		if(vendedor!= null){
			for(Venda venda: vendedor.getVendas()){
			
      out.write("\t\r\n");
      out.write("\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><center>");
      out.print(venda.getNumeroVenda() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
      out.print( venda.getValorVenda() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t<td><center>");
      out.print( venda.getRegiao() );
      out.write("</center></td>\r\n");
      out.write("\t\t\t\t\t");
 qtde++;
					   total += venda.getValorVenda(); 
					
      out.write("\r\n");
      out.write("\t\t\t\t</tr>\r\n");
      out.write("\t\t\t");
		
			}
		}
		
      out.write("\r\n");
      out.write("\t\t</table><br>\r\n");
      out.write("\t\t");
 
			if(vendedor!= null){
			
      out.write("\r\n");
      out.write("\t\t\t<div>\r\n");
      out.write("\t\t\t\tNOME: ");
      out.print( vendedor.getNome());
      out.write("<br>\r\n");
      out.write("\t\t\t\tQUANTIDADE DE VENDAS: ");
      out.print(qtde);
      out.write("<br>\r\n");
      out.write("\t\t\t\tTOTAL: ");
      out.print(total);
      out.write("\r\n");
      out.write("\t\t\t</div><br><br>\r\n");
      out.write("\t\t\t");
 
			}
		
      out.write("\r\n");
      out.write("\t\t<a href=\"Menu.jsp\">VOLTAR</a><br>\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
